/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.server.gui;

import game.server.common.CommonMethod;
import game.server.socket.DayXeHangGameServer;

/**
 *
 * @author tkv-nhukhanhdinh
 */
public class SokobanTest extends javax.swing.JFrame {

    private static SokobanTest sokoban;
    /**
     * Creates new form SokobanTest
     */
    public SokobanTest() {
        initComponents();
    }
    
    public static SokobanTest getSokoban(){
        if(sokoban == null){
            sokoban = new SokobanTest();
        }
        CommonMethod.setLocationFrame(sokoban);
        return sokoban;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top_pain = new javax.swing.JPanel();
        tf_level = new javax.swing.JTextField();
        btn_go = new javax.swing.JButton();
        main_pain = new javax.swing.JPanel();

        btn_go.setText("Test");
        btn_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout top_painLayout = new javax.swing.GroupLayout(top_pain);
        top_pain.setLayout(top_painLayout);
        top_painLayout.setHorizontalGroup(
            top_painLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_painLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(tf_level, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_go)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        top_painLayout.setVerticalGroup(
            top_painLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_painLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(top_painLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_go))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        main_pain.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout main_painLayout = new javax.swing.GroupLayout(main_pain);
        main_pain.setLayout(main_painLayout);
        main_painLayout.setHorizontalGroup(
            main_painLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        main_painLayout.setVerticalGroup(
            main_painLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(top_pain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(main_pain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_pain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(main_pain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goActionPerformed
        String level = tf_level.getText();
        if(CommonMethod.isValidNumber(level)){
            int lvl = Integer.parseInt(level.trim());
            DayXeHangGameServer.setLevel(main_pain.getGraphics(), lvl);
        }
    }//GEN-LAST:event_btn_goActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_go;
    private javax.swing.JPanel main_pain;
    private javax.swing.JTextField tf_level;
    private javax.swing.JPanel top_pain;
    // End of variables declaration//GEN-END:variables
}
